### ISSUE TITLE
SSL metrics - Enhancement with flags section data

### ISSUE THREAD

**Issue by sadmin91** [mtulio/statuscake-exporter#10]
After #5, is it possible to complete SSL metrics available with flags section data available on StatusCake API?

**Comment by mtulio** [comment]
Hi @sadmin91, what mean “complete SSL metrics available with flags section”?
Could you please give samples of desired metrics?

**Comment by sadmin91** [comment]
Hello @mtulio,
On StatusCake API return, a "Flags" section is returned (see below)
![image](https://user-images.githubusercontent.com/6031110/65222870-43f1b200-dac0-11e9-8a6b-9c75a4e73827.png)
Is it possible to create metrics based on theses informations?
Regards

**Comment by mtulio** [comment]
@sadmin91 sure, it's possible! I will open an PR with the solution.

**Comment by mtulio** [comment]
@sadmin91 Fix done in #13, please test with version [v0.4.0-rc1](https://github.com/mtulio/statuscake-exporter/releases/tag/v0.4.0-rc1)

**Comment by sadmin91** [comment]
@mtulio, my tests are successful with release v0.4.0-rc1
