### ISSUE TITLE
PerfData and PerformanceData undefined

### ISSUE THREAD

**Issue by jasonhedges** [mtulio/statuscake-exporter#4]
I cloned your repo and ran make build and I get the following errors:

`
stk/main.go:107:31: stk.client.PerfData undefined (type *statuscake.Client has no field or method PerfData)
`

`
stk/main.go:111:16: stk.Tests[t].PerformanceData undefined (type *statuscake.Test has no field or 
method PerformanceData)
`

It looks like these changes around PerfData may not have been committed to mtulio/statuscake. 

Thanks,
Jason

**Comment by mtulio** [comment]
Hello @jasonhedges , thank you for the report.

This struct is defined inside the StatusCake Go library (https://github.com/mtulio/statuscake/pull/1). I will refact this part on exporter to an better approach (that project is missing some dependencies), maybe on the next week I've finished.

**Comment by mtulio** [comment]
Fixes:
- https://github.com/mtulio/statuscake-exporter/pull/6
--  https://github.com/mtulio/statuscake-exporter/pull/6/files#diff-8eb85af1abaf96bfb35d907656c43e69
- https://github.com/mtulio/statuscake/pull/1

**Comment by mtulio** [comment]
Done https://github.com/mtulio/statuscake-exporter/releases/tag/v0.2.2
