### ISSUE TITLE
Add SSL metrics

### ISSUE THREAD

**Issue by sadmin91** [mtulio/statuscake-exporter#5]
Is it possible to add SSL metrics ?
For example
- SSL Alert Reminder: boolean for AlertReminder data
- SSL Alert Expiry: boolean for AlertExpiry data
- SSL Alert Broken: boolean for AlertBroken data
- SSL Alert Mixed: boolean for AlertMixed data
- SSL Valid Until: timestamp for ValidUntilUtc data

**Comment by mtulio** [comment]
Hello @sadmin91 , Yes, it's possible. I just check that the SSL support was [recently added to the library](https://github.com/DreamItGetIT/statuscake/blob/master/ssl.go).

**Comment by mtulio** [comment]
@sadmin91 please have a look in https://github.com/mtulio/statuscake-exporter/pull/7 and tell me what do you think.

**Comment by sadmin91** [comment]
@mtulio, it's seem fine !
Thanks.

**Comment by sadmin91** [comment]
@mtulio, could you give me a release date for this enhancement?

**Comment by mtulio** [comment]
@sadmin91 sorry by the delay, I just generate a new release, [v0.3.0](https://github.com/mtulio/statuscake-exporter/releases/tag/v0.3.0).
TODO #8

**Comment by sadmin91** [comment]
@mtulio, is it possible to enhancent metrics available with flags section data?
